-- 1. Notification Masters (Templates)
CREATE TABLE IF NOT EXISTS notification_masters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    body_template VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- 2. Users Table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_username_lower ON users (LOWER(username));

-- 3. Notification Subscriptions (FCM Tokens)
CREATE TABLE IF NOT EXISTS notification_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_id VARCHAR(255),
    user_id VARCHAR(255),
    fcm_token VARCHAR(255) NOT NULL UNIQUE,
    device_type VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sub_user_id ON notification_subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_sub_guest_id ON notification_subscriptions(guest_id);

-- 4. Notification Schedules
CREATE TABLE IF NOT EXISTS notification_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT NOT NULL REFERENCES notification_masters(id),
    schedule_type VARCHAR(255) NOT NULL,
    time_of_day TIME WITHOUT TIME ZONE,
    offsets VARCHAR(255),
    interval_minutes INTEGER,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- 5. Notification Schedule Executions (Idempotency)
CREATE TABLE IF NOT EXISTS notification_schedule_executions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id BIGINT NOT NULL,
    recipient_type VARCHAR(255) NOT NULL,
    recipient_id VARCHAR(255) NOT NULL,
    occurrence_key VARCHAR(255) NOT NULL,
    notification_log_id BIGINT,
    executed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(255) NOT NULL,
    CONSTRAINT uk_sched_exec_idemp UNIQUE (schedule_id, recipient_type, recipient_id, occurrence_key)
);
CREATE INDEX IF NOT EXISTS idx_sched_exec_lookup ON notification_schedule_executions(schedule_id, recipient_type, recipient_id, occurrence_key);

-- 6. Notification Logs
CREATE TABLE IF NOT EXISTS notification_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255),
    guest_id VARCHAR(255),
    template_id BIGINT,
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    code VARCHAR(255),
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    read_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_notif_log_user_id ON notification_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_notif_log_guest_id ON notification_logs(guest_id);

-- 7. ShedLock Table
CREATE TABLE IF NOT EXISTS shedlock (
    name VARCHAR(64) NOT NULL PRIMARY KEY,
    lock_until TIMESTAMP NOT NULL,
    locked_at TIMESTAMP NOT NULL,
    locked_by VARCHAR(255) NOT NULL
);
